### ISSUE TITLE
Make sure local dev cycle and CI/CD are aligned

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#194]
## Description 
Pre-commit hooks are not always aligned with CI checks. 

## Implementation 
- make pre-commit on CI required
- remove other ci checks that overlap with pre-commit
- add other linters (and husky?) to pre-commit
- move configuration out of pre-commit to the pyproject.toml

**Comment by laurensWe** [comment]
https://github.com/pre-commit/pre-commit/issues/1165 -> not possible to let pre-commit use config from pyproject.toml

**Comment by anneschuth** [comment]
Harsh thread 😅 

I think we can still tell individual tools to use the pyproject.toml file like this:

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--config, pyproject.toml]
      - id: ruff-format
        args: [--config, pyproject.toml]
```
