### ISSUE TITLE
Ignore babel timestamp diffs

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#237]
This should will help set up a pre-commit hook to automatically remove timestamps from PO files before committing, preventing merge conflicts.

## Step 1: Create the PO file handler script

Create a file named `po_file_handler.py` in the `scripts` folder:
```python
#!/usr/bin/env python
import argparse
from babel.messages import pofile

def remove_timestamps(filename):
    with open(filename, 'rb') as f:
        catalog = pofile.read_po(f)
    
    modified = False
    if catalog.creation_date or catalog.revision_date:
        catalog.creation_date = None
        catalog.revision_date = None
        modified = True
    
    if modified:
        with open(filename, 'wb') as f:
            pofile.write_po(f, catalog, ignore_obsolete=True, include_previous=True)
    
    return modified

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames', nargs='*')
    args = parser.parse_args()

    return_code = 0
    for filename in args.filenames:
        if remove_timestamps(filename):
            print(f"Removed timestamps from {filename}")
            return_code = 1
    return return_code

if __name__ == '__main__':
    exit(main())
```

make the file executable

## Step 2: Create or update the pre-commit configuration

Create or update the `.pre-commit-config.yaml` file in your repository root:

```yaml
repos:
- repo: local
  hooks:
  - id: po-file-handler
    name: PO file timestamp remover
    entry: python po_file_handler.py
    language: python
    files: \.(po|pot)$
    stages: [commit]
    additional_dependencies: ['babel==2.15.0']  # Specify the version you need
```
